		CREATE TABLE V2_PROPERTY (
				  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
				  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
				  CONSTRAINT V2_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
		); 		
        
		COMMENT ON TABLE "V2_PROPERTY"  IS '애플리케이션 전역에서 사용되는 프로퍼티 정보';
		COMMENT ON COLUMN "V2_PROPERTY"."PROPERTY_NAME" IS '프로퍼디 이름'; 
        COMMENT ON COLUMN "V2_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값';
        
        
		CREATE TABLE MUSI_SEQUENCER (
		    SEQUENCER_ID           INTEGER NOT NULL,
		    NAME                   VARCHAR2(200) NOT NULL,
		    VALUE                  INTEGER NOT NULL,
		    CONSTRAINT MUSI_SEQUENCER_PK PRIMARY KEY (SEQUENCER_ID)
		); 			
		
		CREATE UNIQUE INDEX MUSI_SEQUENCER_NAME_IDX ON MUSI_SEQUENCER (NAME);		
        
		COMMENT ON TABLE "MUSI_SEQUENCER"  IS '애플리케이션 전역에서 사용되는 시퀀서 정보';
		COMMENT ON COLUMN "MUSI_SEQUENCER"."SEQUENCER_ID" IS '시퀀서 ID'; 
        COMMENT ON COLUMN "MUSI_SEQUENCER"."NAME" IS '시퀀서 이름';		
		COMMENT ON COLUMN "MUSI_SEQUENCER"."VALUE" IS '시퀀서 값';		
		
		
		-- User
		CREATE TABLE MUSI_USER (
		  USER_ID                INTEGER NOT NULL,
		  USERNAME               VARCHAR2(100) NOT NULL,
		  PASSWORD_HASH          VARCHAR2(64)  NOT NULL,
		  NAME                   VARCHAR2(100),		  
		  NAME_VISIBLE           NUMBER(1, 0)  DEFAULT 1 ,
		  FIRST_NAME             VARCHAR2(100),		  
		  LAST_NAME              VARCHAR2(100),		
		  EMAIL                  VARCHAR2(100) NOT NULL,
		  EMAIL_VISIBLE          NUMBER(1, 0)  DEFAULT 1,
		  USER_ENABLED           NUMBER(1, 0)  DEFAULT 1, 
		  STATUS                 NUMBER(1, 0)  DEFAULT 0,
		  CREATION_DATE          DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE          DATE DEFAULT  SYSDATE NOT NULL,		    
		  CONSTRAINT MUSI_USER_PK PRIMARY KEY (USER_ID)
		);		
		
		CREATE UNIQUE INDEX MUSI_USER_IDX_USERNAME ON MUSI_USER (USERNAME);
		
		COMMENT ON TABLE  "MUSI_USER"  IS '사용자 테이블';
		COMMENT ON COLUMN "MUSI_USER"."USER_ID" IS 'ID'; 
		COMMENT ON COLUMN "MUSI_USER"."USERNAME" IS '로그인 아이디'; 
        COMMENT ON COLUMN "MUSI_USER"."NAME" IS '전체 이름';
		COMMENT ON COLUMN "MUSI_USER"."PASSWORD_HASH" IS '암호화된 패스워드'; 
        COMMENT ON COLUMN "MUSI_USER"."NAME_VISIBLE" IS '이름 공개 여부';        
		COMMENT ON COLUMN "MUSI_USER"."FIRST_NAME" IS '이름'; 
        COMMENT ON COLUMN "MUSI_USER"."LAST_NAME" IS '성';        
		COMMENT ON COLUMN "MUSI_USER"."EMAIL" IS '메일주소'; 
        COMMENT ON COLUMN "MUSI_USER"."EMAIL_VISIBLE" IS '메일주소 공개여부';           
		COMMENT ON COLUMN "MUSI_USER"."USER_ENABLED" IS '계정 사용여부';     
        COMMENT ON COLUMN "MUSI_USER"."STATUS" IS '계정 상태';	    
        COMMENT ON COLUMN "MUSI_USER"."CREATION_DATE" IS '생성일자';	    
        COMMENT ON COLUMN "MUSI_USER"."MODIFIED_DATE" IS '수정일자';	
        
        -- Role
		CREATE TABLE MUSI_ROLE (
		  ROLE_ID                     INTEGER NOT NULL,
		  NAME                        VARCHAR2(100)   NOT NULL,
		  DESCRIPTION              VARCHAR2(1000)  NOT NULL,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT MUSI_ROLE_PK PRIMARY KEY (ROLE_ID)
		);
		
		COMMENT ON TABLE "MUSI_ROLE"  IS '롤 테이블';
		COMMENT ON COLUMN "MUSI_ROLE"."ROLE_ID" IS '롤 ID'; 
		COMMENT ON COLUMN "MUSI_ROLE"."NAME" IS '롤 이름'; 
		COMMENT ON COLUMN "MUSI_ROLE"."DESCRIPTION" IS '설명'; 	
		COMMENT ON COLUMN "MUSI_ROLE"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "MUSI_ROLE"."MODIFIED_DATE" IS '수정일자'; 				
		
		CREATE UNIQUE INDEX MUSI_ROLE_NAME_IDX ON V2_ROLE (NAME)
		
		-- User Roles 
		CREATE TABLE MUSI_USER_ROLES (
		  USER_ID                 INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT MUSI_USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID)
		);

		COMMENT ON TABLE "MUSI_USER_ROLES"  IS '사용자 롤 테이블';
		COMMENT ON COLUMN "MUSI_USER_ROLES"."USER_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "MUSI_USER_ROLES"."ROLE_ID" IS '롤 ID'; 
        